const fs = require("fs"); 
require("dotenv").config();

module.exports = {
    prefix: process.env.PREFIX || ".",
    ownerName: process.env.OWNER_NAME || "Toxxic-Boy",
    ownerNumber: process.env.OWNER_NUMBER || "243892839065",
    mode: process.env.MODE || "public",
    region: process.env.REGION || "Nigeria",
    botName: process.env.BOT_NAME || "Rias Gremory V3",
    exifPack: process.env.EXIF_PACK || "RIAS V3 LOVES",
    exifAuthor: process.env.EXIF_AUTHOR || "Toxxic",
    timeZone: process.env.TIME_ZONE || "Africa/Lagos",
    presenceStatus: process.env.PRESENCE_STATUS || "unavailable",
    autoRead: process.env.AUTO_READ === "true",
    autoViewStatus: process.env.AUTO_VIEW_STATUS === "true",
    autoReact: process.env.AUTO_REACT === "true",
    sessionId: process.env.SESSION_ID || "Zokou-MD-WHATSAPP-BOT;;;=>eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTUlmZVFxa2VzS1JmK2ZCcjNHbXVSKzBGQXpuQS84SSsxUVVGMTJUa0JuUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR1FJcmM5K0xvcjBJWm5WSUp3R21NVUlpTWgxU1RZRU9GbkN2UGl0TXdFZz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI0Rk0wTmp1ZjgvOXJDcVMwMHV1dnVvVEtMdjY5aXp6ZkhXbDAyV3Y5cDE4PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJnUEhSb1NiaVE4akVSaG9vZnRlaUJYWUY0SUgyMU9GQ2lDNnFIQU90QVRjPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjBNaDJnWWllaFB5SVhVdjc2ekFDYmw4VlJ1WDVkSDU1QVBYWXUrVnFYRms9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9WM1E5MmdpTEVtKzBlTEc3RG9qY2dQN0VLbjFDY3BkTkdUNUZXeDE2UVk9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR0lBWjJydU9pWkZDSW5TQzF1dURXZVBGVU0rTXAzMkZLZjMvU3E4eTRraz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTkdRSXdPWWVpd3lHZmwwRTJaZ0I2b1g1N3RwMjhDcWlGcGFLbEYyVHBHOD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImFHZFBDOWVSWEswcWJiVm9id0lWaVlhYlJ0YzVrYUp2dmVEYnJNUHZLRkRkRTRFclJ0NUxqVThOcnI4V3ptb01hei8wZStyVFZhVkZ5WFpKZGhDMWdBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjExLCJhZHZTZWNyZXRLZXkiOiJqZzlIa3g2cGhzSmJRNVZ5VTl1ZmFjTWVMVzNqRElCelRFejd3UHRpdGZvPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJYWTNQTVRFRyIsImxhc3RQcm9wSGFzaCI6IjJHNEFtdSIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0JJSURRPT0ifSwibWUiOnsiaWQiOiIyNDM4OTI4MzkwNjU6M0BzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiLwnZWB8J2UuOKEmeKEjfCdlLzwnZWLX/CdlL7wnZS48J2VgPCdlYPwnZWD8J2UuOKEnfCdlLsiLCJsaWQiOiIzMDg0NzA1OTEwMzkzMDozQGxpZCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTVhKMXpzUWxiT1l2UVlZQVNBQUtBQT0iLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiUVNKNGpRd09lOFNQQXN3Yk5pYnV2anl4R2FYTzBaR0lsVVFqUE9PQ1pVWT0iLCJhY2NvdW50U2lnbmF0dXJlIjoiTFdZanJ5cEVGa0dEQU01UlV3TDRVT05JczNoYXUwZlE0WnAwU1dEYXVwSE1tZHZMNXY0d2c4SDhKcXRTVjRzejIxVnp4bGp5QlgrcE9SNFdESFRYQkE9PSIsImRldmljZVNpZ25hdHVyZSI6Ikh3TWpQb25jaWYwN1llRThlU2haSkpHV2lzbklhcWMxNC9tSHAyOTZwNWtGT2tKeXRFc3FxNEx6NFNFUHFIQVU0ZHF5cXliNW9PUUhqNmpkM3VMaGpBPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjQzODkyODM5MDY1OjNAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCVUVpZUkwTURudkVqd0xNR3pZbTdyNDhzUm1senRHUmlKVkVJenpqZ21WRyJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczODkzODc3NiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFHTzEifQ==",
    autoRejectEnabled: process.env.AUTO_REJECT_ENABLED || "false",
};

let file = require.resolve(__filename); 
fs.watchFile(file, () => {
    fs.unwatchFile(file); 
    console.log(`Update '${__filename}'`); 
    delete require.cache[file];
    require(file); 
});
